### ISSUE TITLE
iOS 9 Universal Deep Links

### ISSUE THREAD

**Issue by chrisballinger** [zom/zom.github.io#1]
Here's some guides on how to do this:
- https://blog.branch.io/how-to-setup-universal-links-to-deep-link-on-apple-ios-9

**Comment by n8fr8** [comment]
Seems like we can't use cloudflare or github, since we have to use their SSL certs, and to enable this we need to be able to sign with an SSL private key:

"i. Buy a domain name or pick from your existing

ii. Acquire SSL certification for the domain name

iii. Create structured ‘apple-app-site-association’ JSON file

iv. Sign the JSON file with the SSL certification

v. Configure the file server"

**Comment by n8fr8** [comment]
actually, nevermind - Apple doesn't include the "sign the json file" step:
https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html

**Comment by n8fr8** [comment]
Also @chrisballinger I need the full appId:

"Each app-specific dictionary contains an appID key and a paths key. The value of the appID key is the app’s team ID and the bundle ID"

**Comment by n8fr8** [comment]
Okay, cloudflare is setup and in process... https://zom.im should soon be fronting out https://zom.github.io

**Comment by n8fr8** [comment]
almost there... zom.im is pointing at the right place, but the certificate is screwed up for htttps

http://zom.im/apple-app-site-association is a valid file that exists now

**Comment by n8fr8** [comment]
okay https://zom.im/ is alive now, and https://zom.im/apple-app-site-association works!

**Comment by n8fr8** [comment]
Please let me know if this looks legit: https://github.com/zom/zom.github.io/blob/master/apple-app-site-association

**Comment by N-Pex** [comment]
I think we need the Team ID prepended to the appID entry in this file, like "appID": "TEAMXYZ.im.zom.zom". But I guess we don't have the team ID yet.
